### ISSUE TITLE
If possible,what about add automated change setting?

### ISSUE THREAD

**Issue by Panamaz** [luisflorido/wallhaven-desktop#2]
Your applicalition is wonderful !!
 But in macos,there is still no app can get wallheaven's pictures and automateky set to the screen.
Hope you can realize it!

**Comment by luisflorido** [comment]
Thanks! I thought about this feature but gave up since you can set your download folder as a default folder for mac wallpapers, if you still think this feature can be useful let me know!

**Comment by Panamaz** [comment]
Thanks for your reply!
I think your app is the only independent app for mac using wallheaven’s wallpaper. I really appreciate it.
Of course, we can set a folder as a place to switch downloaded wallpapers, while if we can switch pictures only automatically by random scratch in website，and the pictures we set are cached, maybe it will be another way to use amost limitless pictures.

发件人: Luis ***@***.***>
日期: 星期三, 2023年3月15日 08:37
收件人: luisflorido/wallhaven-desktop ***@***.***>
抄送: Panamaz ***@***.***>, Author ***@***.***>
主题: Re: [luisflorido/wallhaven-desktop] If possible,what about add automated change setting? (Issue #2)

Thanks! I thought about this feature but gave up since you can set your download folder as a default folder for mac wallpapers, if you still think this feature can be useful let me know!

―
