### ISSUE TITLE
Wallpaper dynamic thumbnails

### ISSUE THREAD

**Issue by CreativeC0der** [luisflorido/wallhaven-desktop#3]
Kudos for making this great app!! 
It Would be really helpful if the thumbnails were dynamic according to their aspect ratios. Currently everything is a square. Also considering the fact that this is a desktop application.
Thank you and good day to you;)

**Comment by luisflorido** [comment]
Hi, sorry for the delay to answering, I'll try to do that in this week, thank you :)

**Comment by CreativeC0der** [comment]
Any ETA for this feature??

**Comment by luisflorido** [comment]
@CreativeC0der sorry for taking too long to do, it's available on the new version https://github.com/luisflorido/wallhaven-desktop/releases/tag/v1.0.2, it is still unfinished, so it's not beautiful and may have some bugs

**Comment by CreativeC0der** [comment]
Good enough for ME. Thank you DEV. Kudos and have a great day!!
