### ISSUE TITLE
Download Progress

### ISSUE THREAD

**Issue by ArchismanKarmakar** [luisflorido/wallhaven-desktop#6]
I am having a look into this repository, and I will definitely try my best to add a progress bar for downloads. Thanks.

**Comment by luisflorido** [comment]
Thank you! Will be very helpful

**Comment by ArchismanKarmakar** [comment]
@luisflorido I have added the Progress bar, although I have not added the functioning and visuals because the main window has no place to show the progress bar. Firstly, I think it's better to add a status bar then add the rest of the items.

**Comment by luisflorido** [comment]
This weekend I'll look into that, thank you man!

**Comment by luisflorido** [comment]
I used your PR and finished the functionality, thank you!
